# -*- coding: utf-8 -*-
"""Notas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bowRJfU7UBUQQhCG7Io8o_4kRspK2-x9
"""

nome = input("Insira seu nome: ")

nota1 = float(input("Sua primeira nota: "))
nota2 = float(input("Sua segunda nota: "))

print("Ola", nome, "suas notas foram:")
print(nota1, "e", nota2)

soma = nota1 + nota2 
media = soma/2

print("Sua media e", media)

